name: CI/CD with SonarCloud

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set_up_JDK 17
        uses: actions/setup-java@v1
        with:
           java-version: 17  # Use the appropriate Java version

      - name: Build with Maven
        run: mvn clean install

      - name: Run SonarCloud Analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=vaibhav-kadam-13 
            -Dsonar.organization=$SONAR_ORGANIZATION 
            -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
